/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.genai.types.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.google.auto.value.AutoValue;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.genai.JsonSerializable;
import com.google.genai.types.ExcludeFromGeneratedCoverageReport;
import java.util.Optional;

/**
 * Citation information for model-generated content in the Interactions API.
 *
 * <p>Annotations provide attribution for specific segments of text by mapping byte indices to their
 * source references (such as URLs or titles). This enables proper citation and source tracking for
 * content generated by the model.
 *
 * <p>Example usage:
 *
 * <pre>{@code
 * Annotation citation = Annotation.builder()
 *     .startIndex(0)
 *     .endIndex(50)
 *     .source("https://example.com/research-paper")
 *     .build();
 *
 * // Or using the convenience factory method
 * Annotation citation2 = Annotation.of(51, 100, "Wikipedia: Machine Learning");
 * }</pre>
 *
 * <p>The Interactions API is available in both Vertex AI and Gemini API.
 *
 * <p>Note: The Interactions API is in beta and subject to change.
 */
@AutoValue
@JsonDeserialize(builder = Annotation.Builder.class)
public abstract class Annotation extends JsonSerializable {

  /**
   * Start of segment of the response that is attributed to this source. Index indicates the start
   * of the segment, measured in bytes.
   */
  @JsonProperty("start_index")
  public abstract Optional<Integer> startIndex();

  /**
   * End of the attributed segment, exclusive. Index indicates the end of the segment, measured in
   * bytes.
   */
  @JsonProperty("end_index")
  public abstract Optional<Integer> endIndex();

  /** Source attributed for a portion of the text. Could be a URL, title, or other identifier. */
  @JsonProperty("source")
  public abstract Optional<String> source();

  /** Instantiates a builder for Annotation. */
  @ExcludeFromGeneratedCoverageReport
  public static Builder builder() {
    return new AutoValue_Annotation.Builder();
  }

  /** Creates a builder with the same values as this instance. */
  public abstract Builder toBuilder();

  /** Builder for Annotation. */
  @AutoValue.Builder
  public abstract static class Builder {
    /** For internal usage. Please use {@code Annotation.builder()} for instantiation. */
    @JsonCreator
    private static Builder create() {
      return new AutoValue_Annotation.Builder();
    }

    /**
     * Setter for startIndex.
     *
     * <p>startIndex: Start of segment of the response that is attributed to this source.
     */
    @JsonProperty("start_index")
    public abstract Builder startIndex(Integer startIndex);

    @ExcludeFromGeneratedCoverageReport
    abstract Builder startIndex(Optional<Integer> startIndex);

    /** Clears the value of startIndex field. */
    @ExcludeFromGeneratedCoverageReport
    @CanIgnoreReturnValue
    public Builder clearStartIndex() {
      return startIndex(Optional.empty());
    }

    /**
     * Setter for endIndex.
     *
     * <p>endIndex: End of the attributed segment, exclusive.
     */
    @JsonProperty("end_index")
    public abstract Builder endIndex(Integer endIndex);

    @ExcludeFromGeneratedCoverageReport
    abstract Builder endIndex(Optional<Integer> endIndex);

    /** Clears the value of endIndex field. */
    @ExcludeFromGeneratedCoverageReport
    @CanIgnoreReturnValue
    public Builder clearEndIndex() {
      return endIndex(Optional.empty());
    }

    /**
     * Setter for source.
     *
     * <p>source: Source attributed for a portion of the text.
     */
    @JsonProperty("source")
    public abstract Builder source(String source);

    @ExcludeFromGeneratedCoverageReport
    abstract Builder source(Optional<String> source);

    /** Clears the value of source field. */
    @ExcludeFromGeneratedCoverageReport
    @CanIgnoreReturnValue
    public Builder clearSource() {
      return source(Optional.empty());
    }

    public abstract Annotation build();
  }

  /** Deserializes a JSON string to an Annotation object. */
  @ExcludeFromGeneratedCoverageReport
  public static Annotation fromJson(String jsonString) {
    return JsonSerializable.fromJsonString(jsonString, Annotation.class);
  }

  /** Convenience factory method. */
  @ExcludeFromGeneratedCoverageReport
  public static Annotation of(Integer startIndex, Integer endIndex, String source) {
    return builder().startIndex(startIndex).endIndex(endIndex).source(source).build();
  }
}
